//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default {
			get {
				return defaultInstance;
			}
		}

		public string CalcTextDLogTitol { get; internal set; }
		public string CalcTexWidth { get; internal set; }
		public string CalcTextFontSize { get; internal set; }
		public string CalcTextShowX { get; internal set; }
		public string CalcTextShowY { get; internal set; }
		public string CalcWindowWidthStr { get; internal set; }
		public string CalcWindowHeightStr { get; internal set; }
		public string CalcResult { get; internal set; }
	}
}
