//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleOSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public int Id { get; set; }
        public string Color_var { get; set; }
        public string Color_name { get; set; }
        public string google_Color_id { get; set; }
        public Nullable<System.DateTime> modifier_on { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }
    }
}
