CREATE TABLE [dbo].t_events
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [m_contract_id] INT NULL, 
    [t_project_base_id] INT NULL, 
    [event_type] TINYINT NULL,
    [event_date_start] DATE NULL, 
    [event_time_start] TINYINT NULL, 
    [event_date_end] DATE NULL, 
    [event_time_end] TINYINT NULL, 
    [event_is_daylong] TINYINT NULL, 
    [event_title] VARCHAR(255) NULL, 
    [event_place] VARCHAR(255) NULL, 
    [event_memo] VARCHAR(4000) NULL, 
    [event_status] TINYINT NULL, 
    [google_id] VARCHAR(100) NULL, 
    [event_bg_color] VARCHAR(10) NULL, 
    [event_font_color] VARCHAR(10) NULL, 
    [project_name] VARCHAR(255) NULL, 
    [project_number] VARCHAR(255) NULL, 
    [order_number] VARCHAR(255) NULL, 
    [management_number] VARCHAR(255) NULL, 
    [owner_name] VARCHAR(255) NULL, 
)
