//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleOSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_events
    {
        public int Id { get; set; }
        public Nullable<int> m_contract_id { get; set; }
        public Nullable<int> t_project_base_id { get; set; }
        public Nullable<byte> event_type { get; set; }
        public Nullable<System.DateTime> event_date_start { get; set; }
        public Nullable<byte> event_time_start { get; set; }
        public Nullable<System.DateTime> event_date_end { get; set; }
        public Nullable<byte> event_time_end { get; set; }
        public Nullable<byte> event_is_daylong { get; set; }
        public string event_title { get; set; }
        public string event_place { get; set; }
        public string event_memo { get; set; }
        public Nullable<byte> event_status { get; set; }
        public string google_id { get; set; }
        public string event_bg_color { get; set; }
        public string event_font_color { get; set; }
        public string project_name { get; set; }
        public string project_number { get; set; }
        public string order_number { get; set; }
        public string management_number { get; set; }
        public string owner_name { get; set; }
		public Nullable<byte> status { get; set; }
		public Nullable<System.DateTime> modifier_on { get; set; }
		public Nullable<System.DateTime> deleted_on { get; set; }
	}
}
