//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleOSD
{
	using System;
	using System.Collections.Generic;
	using MySql.Data.MySqlClient;

	public partial class t_project_base
    {
        public int Id { get; set; }
        public Nullable<int> m_contract_id { get; set; }
        public Nullable<int> m_property_id { get; set; }
        public string project_number { get; set; }
        public string order_number { get; set; }
        public string project_code { get; set; }
        public string project_manage_code { get; set; }
        public string project_name { get; set; }
        public string management_number { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string supplier_name { get; set; }
        public string owner_name { get; set; }
        public string project_place { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> modifier_on { get; set; }
        public Nullable<System.DateTime> deleted_on { get; set; }

	}
}
